#!/usr/bin/env bash

set -x
set -e

PERCENTAGE=${1:-25}

DEST=`pwd`
cd /tmp

bash <<EOF
set -x; mapshaper -i "${SHAPE}" -simplify ${PERCENTAGE}% -o force # 2> /dev/null
EOF

$DEST/shp2json "${SHAPE}"

# $DEST/cleangeojson

# rm out.json
mv *.json $DEST

cd $DEST

find -name '*.json' -exec du -h {} \;
