#!/usr/bin/env bash
DEST=`pwd`
cd /tmp

URL="http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip"
FILE="${URL##*/}"
curl -sLOk "${URL}" -o ${FILE}
unzip $FILE

SHAPE=$(ls *.shp)
echo $SHAPE
mapshaper -i "${SHAPE}" -simplify 25% -o
shp2json "${SHAPE}"

cleangeojson

rm out.json
mv *.json $DEST